#server:
#    port: 8022
#spring:
#  application:
#    name: provider
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8010/eureka/
#  instance:
#    prefer-ip-address: true
