server:
  port: 8040
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
    instance:
      prefer-ip-address: true
zuul:
  routes:
    provider: /p/**
    consumer: /c/**