server:
  port: 8120
spring:
  zipkin:
    base-url: http://localhost:9411/
    service:
      name: zipkinclient
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  application:
    name: zipkinclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
  instance:
    prefer-ip-address: true