server:
  port: 8101
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LLJLS/springcloud.git
          search-paths: config
          username: 1727101542@qq.com
          password: zaxgithub123456tlx
      label: master
  application:
    name: remoteconfigserver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
  instance:
    prefer-ip-address: true
