server:
  port: 8050
spring:
  application:
    name: ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
    instance:
      prefer-ip-address: true
